name: Build Readme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  update-social:
    runs-on: ubuntu-latest
    steps:
      - uses: zylele/social-readme@master
        with:
          douban_name: sjx270992395
          douban_limit: 5
