name: Update events

on:
  watch:
    types: started
  schedule:
    - cron:  '0 8 * * *'

jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Check out repo
#       uses: actions/checkout@v2
#     - uses: actions/setup-go@v2
#     - name: Fetch events
#       run: go run main.go
#     - name: Commit and push
#       run: |-
#         git config --global user.email "bot@github.com" && git config --global user.name "Bot"
#         git diff
#         git add . && git commit -m ":memo: 更新自述" || exit 0
#         git push
  update-social:
    runs-on: ubuntu-latest
    steps:
      - name: Social Readme
        uses: zylele/social-readme@master
        with:
          blog_rss_link: https://achuan-2.top/atom.xml
          blog_limit: 10
          douban_name: sjx270992395
          douban_limit: 10
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg

